/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData battery_0 = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_25 = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_50 = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_75 = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_100 = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v_battery_4 = IconData(0xf240, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v_battery_3 = IconData(0xf241, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v_battery_2 = IconData(0xf242, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v_battery_1 = IconData(0xf243, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v_battery_0 = IconData(0xf244, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
